name: Build

on:
  push:
    branches-ignore:
      - "dependabot/**"
  pull_request:

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6
  android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Setup JDK
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5.7.0
        with:
          distribution: 'temurin'
          cache: 'gradle'
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0
        with:
          cache-provider: basic
      - name: Use dummy google-services json
        run: mv androidApp/src/google-services-dummy.json androidApp/src/google-services.json
      - name: Build and Test
        run: ./gradlew :androidApp:assembleDebug testDebugUnitTest testAndroidHostTest jvmTest lintDebug
        env:
          GITHUB_ACTOR: ${{ secrets.READ_PACKAGES_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.READ_PACKAGES_TOKEN }}

  ios:
    runs-on: macos-15
    steps:
      - name: Checkout source
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: recursive
      - name: Setup JDK
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5.7.0
        with:
          distribution: 'temurin'
          cache: 'gradle'
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0
        with:
          cache-provider: basic
      - name: Set up Xcode
        run: |
          ls /Applications/Xcode*
          swift --version
          sudo xcode-select --switch /Applications/Xcode_26.2.app/Contents/Developer
      - name: Use dummy google-services json
        run: mv androidApp/src/google-services-dummy.json androidApp/src/google-services.json
      - name: Build
        run: ./gradlew :composeApp:compileKotlinIosArm64 :libpebble3:linkDebugFrameworkIosArm64
        env:
          GITHUB_ACTOR: ${{ secrets.READ_PACKAGES_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.READ_PACKAGES_TOKEN }}
